name: apotek-sehat-dev

services:
  apotek-sehat-postgres:
    image: postgres:17
    container_name: apotek_segat_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRE_DB}
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - "${POSTGRE_PORT}:5432"
    env_file:
      - .env
    volumes:
      - apotek_sehat_postgre_data:/var/lib/postgresql/data
    networks:
      - apotek_sehat_network

networks:
  apotek_sehat_network:

volumes:
  apotek_sehat_postgre_data: